trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  R_VERSION: '4.3.1'

jobs:
  - job: Build
    displayName: "Build R Shiny App"
    steps:
      - script: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev gdebi-core
        displayName: 'Install system dependencies'

      - script: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 'E298A3A825C0D65DFD57CBB651716619E084DAB9'
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/"
          sudo apt-get update -y
          sudo apt-get install -y r-base
        displayName: 'Install R'

      - script: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'
        displayName: 'Restore R environment with renv'

      - script: |
          Rscript -e 'install.packages("rsconnect", repos = "https://cloud.r-project.org")'
        displayName: 'Install rsconnect'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '.'  # Path to publish
          ArtifactName: 'bioage-app'
          publishLocation: 'Container'

  - job: Deploy
    displayName: "Deploy to shinyapps.io"
    dependsOn: Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'bioage-app'
          downloadPath: '$(System.DefaultWorkingDirectory)/bioage-app'

      - script: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev gdebi-core r-base
        displayName: 'Install R and dependencies'

      - script: |
          echo "Installing rsconnect and setting account info..."
          Rscript -e 'install.packages("rsconnect", repos = "https://cloud.r-project.org")'
          Rscript -e '
            rsconnect::setAccountInfo(
              name = Sys.getenv("SHINYAPPS_NAME"),
              token = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            )
          '
        env:
          SHINYAPPS_NAME: $(SHINYAPPS_NAME)
          SHINYAPPS_TOKEN: $(SHINYAPPS_TOKEN)
          SHINYAPPS_SECRET: $(SHINYAPPS_SECRET)
        displayName: 'Configure rsconnect'

      - script: |
          Rscript -e '
            rsconnect::deployApp(
              appDir = "$(System.DefaultWorkingDirectory)/bioage-app",
              appName = "bioage-otp-auth",
              account = Sys.getenv("SHINYAPPS_NAME")
            )
          '
        env:
          SHINYAPPS_NAME: $(SHINYAPPS_NAME)
          SHINYAPPS_TOKEN: $(SHINYAPPS_TOKEN)
          SHINYAPPS_SECRET: $(SHINYAPPS_SECRET)
        displayName: 'Deploy Shiny App'
