name: CI/CD - v1.3.0 OTP Auth

on:
  push:
    branches:
      - v1.3.0-OTP-Auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
        restore-keys: ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb-dev

    - name: Restore dependencies
      run: |
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::restore()'

    - name: Lint code
      run: |
        Rscript -e 'install.packages("lintr")'
        Rscript -e 'lintr::lint_dir()'

    - name: Run tests
      run: |
        Rscript -e 'install.packages("testthat")'
        Rscript -e 'testthat::test_dir("test/testthat")'

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e 'install.packages("rsconnect")'
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_ACCOUNT'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "rsconnect::deployApp(appName=Sys.getenv('SHINYAPPS_NAME'))"
