name: Build and Deploy R Shiny App

on:
  push:
    branches:
      -  v1.3.0-OTP-Auth

env:
  R_VERSION: "4.3.1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install renv and restore packages
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: bioage-app
          path: .

  deploy:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: bioage-app
          path: ./bioage-app

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install rsconnect
        run: |
          Rscript -e 'install.packages("rsconnect", repos = "https://cloud.r-project.org")'

      - name: Set Shinyapps account info and deploy
        run: |
          Rscript -e '
            rsconnect::setAccountInfo(
              name = Sys.getenv("SHINYAPPS_NAME"),
              token = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            )
          '
          Rscript -e '
            rsconnect::deployApp(
              appDir = "./bioage-app",
              appName = "bioage-otp-auth",
              account = Sys.getenv("SHINYAPPS_NAME")
            )
          '
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
